# Platform
TARGET_BOARD_PLATFORM := mt6797
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a53
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53

BOARD_FLASH_BLOCK_SIZE := 4096

# Camera
MTK_CAM_DEFAULT_ZSD_ON_SUPPORT := yes

# exFAT / sdfat
TARGET_EXFAT_DRIVER := sdfat

# Lights
TARGET_PROVIDES_LIBLIGHT := true

# Recovery
TARGET_RECOVERY_UI_MARGIN_HEIGHT := 32
TARGET_RECOVERY_UI_MARGIN_WIDTH  := 32

# Manifest for SHIFT-made HAL
DEVICE_MANIFEST_FILE += device/shift/mt6797-common/manifest.xml
